/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppVistoriasIndexRouteImport } from './routes/app/vistorias.index'
import { Route as AppImoveisIndexRouteImport } from './routes/app/imoveis.index'
import { Route as AppImoveisIdRouteImport } from './routes/app/imoveis.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVistoriasIndexRoute = AppVistoriasIndexRouteImport.update({
  id: '/vistorias/',
  path: '/vistorias/',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisIndexRoute = AppImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisIdRoute = AppImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/imoveis/': typeof AppImoveisIndexRoute
  '/app/vistorias/': typeof AppVistoriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/imoveis': typeof AppImoveisIndexRoute
  '/app/vistorias': typeof AppVistoriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/imoveis/': typeof AppImoveisIndexRoute
  '/app/vistorias/': typeof AppVistoriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/imoveis/$id'
    | '/app/imoveis/'
    | '/app/vistorias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/imoveis/$id'
    | '/app/imoveis'
    | '/app/vistorias'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/imoveis/$id'
    | '/app/imoveis/'
    | '/app/vistorias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vistorias/': {
      id: '/app/vistorias/'
      path: '/vistorias'
      fullPath: '/app/vistorias/'
      preLoaderRoute: typeof AppVistoriasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/': {
      id: '/app/imoveis/'
      path: '/imoveis'
      fullPath: '/app/imoveis/'
      preLoaderRoute: typeof AppImoveisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/$id': {
      id: '/app/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/app/imoveis/$id'
      preLoaderRoute: typeof AppImoveisIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppImoveisIdRoute: typeof AppImoveisIdRoute
  AppImoveisIndexRoute: typeof AppImoveisIndexRoute
  AppVistoriasIndexRoute: typeof AppVistoriasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppImoveisIdRoute: AppImoveisIdRoute,
  AppImoveisIndexRoute: AppImoveisIndexRoute,
  AppVistoriasIndexRoute: AppVistoriasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
