/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppVistoriasIndexRouteImport } from './routes/app/vistorias.index'
import { Route as AppImoveisIndexRouteImport } from './routes/app/imoveis.index'
import { Route as AppVistoriasNovaRouteImport } from './routes/app/vistorias.nova'
import { Route as AppVistoriasIdRouteImport } from './routes/app/vistorias.$id'
import { Route as AppImoveisIdRouteImport } from './routes/app/imoveis.$id'
import { Route as AppCompararABRouteImport } from './routes/app/comparar.$a.$b'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppVistoriasIndexRoute = AppVistoriasIndexRouteImport.update({
  id: '/vistorias/',
  path: '/vistorias/',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisIndexRoute = AppImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => AppRoute,
} as any)
const AppVistoriasNovaRoute = AppVistoriasNovaRouteImport.update({
  id: '/vistorias/nova',
  path: '/vistorias/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppVistoriasIdRoute = AppVistoriasIdRouteImport.update({
  id: '/vistorias/$id',
  path: '/vistorias/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisIdRoute = AppImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCompararABRoute = AppCompararABRouteImport.update({
  id: '/comparar/$a/$b',
  path: '/comparar/$a/$b',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/': typeof AppIndexRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/vistorias/$id': typeof AppVistoriasIdRoute
  '/app/vistorias/nova': typeof AppVistoriasNovaRoute
  '/app/imoveis/': typeof AppImoveisIndexRoute
  '/app/vistorias/': typeof AppVistoriasIndexRoute
  '/app/comparar/$a/$b': typeof AppCompararABRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app': typeof AppIndexRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/vistorias/$id': typeof AppVistoriasIdRoute
  '/app/vistorias/nova': typeof AppVistoriasNovaRoute
  '/app/imoveis': typeof AppImoveisIndexRoute
  '/app/vistorias': typeof AppVistoriasIndexRoute
  '/app/comparar/$a/$b': typeof AppCompararABRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/': typeof AppIndexRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/vistorias/$id': typeof AppVistoriasIdRoute
  '/app/vistorias/nova': typeof AppVistoriasNovaRoute
  '/app/imoveis/': typeof AppImoveisIndexRoute
  '/app/vistorias/': typeof AppVistoriasIndexRoute
  '/app/comparar/$a/$b': typeof AppCompararABRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/configuracoes'
    | '/app/'
    | '/app/imoveis/$id'
    | '/app/vistorias/$id'
    | '/app/vistorias/nova'
    | '/app/imoveis/'
    | '/app/vistorias/'
    | '/app/comparar/$a/$b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/configuracoes'
    | '/app'
    | '/app/imoveis/$id'
    | '/app/vistorias/$id'
    | '/app/vistorias/nova'
    | '/app/imoveis'
    | '/app/vistorias'
    | '/app/comparar/$a/$b'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/configuracoes'
    | '/app/'
    | '/app/imoveis/$id'
    | '/app/vistorias/$id'
    | '/app/vistorias/nova'
    | '/app/imoveis/'
    | '/app/vistorias/'
    | '/app/comparar/$a/$b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vistorias/': {
      id: '/app/vistorias/'
      path: '/vistorias'
      fullPath: '/app/vistorias/'
      preLoaderRoute: typeof AppVistoriasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/': {
      id: '/app/imoveis/'
      path: '/imoveis'
      fullPath: '/app/imoveis/'
      preLoaderRoute: typeof AppImoveisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vistorias/nova': {
      id: '/app/vistorias/nova'
      path: '/vistorias/nova'
      fullPath: '/app/vistorias/nova'
      preLoaderRoute: typeof AppVistoriasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vistorias/$id': {
      id: '/app/vistorias/$id'
      path: '/vistorias/$id'
      fullPath: '/app/vistorias/$id'
      preLoaderRoute: typeof AppVistoriasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/$id': {
      id: '/app/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/app/imoveis/$id'
      preLoaderRoute: typeof AppImoveisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comparar/$a/$b': {
      id: '/app/comparar/$a/$b'
      path: '/comparar/$a/$b'
      fullPath: '/app/comparar/$a/$b'
      preLoaderRoute: typeof AppCompararABRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppImoveisIdRoute: typeof AppImoveisIdRoute
  AppVistoriasIdRoute: typeof AppVistoriasIdRoute
  AppVistoriasNovaRoute: typeof AppVistoriasNovaRoute
  AppImoveisIndexRoute: typeof AppImoveisIndexRoute
  AppVistoriasIndexRoute: typeof AppVistoriasIndexRoute
  AppCompararABRoute: typeof AppCompararABRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppIndexRoute: AppIndexRoute,
  AppImoveisIdRoute: AppImoveisIdRoute,
  AppVistoriasIdRoute: AppVistoriasIdRoute,
  AppVistoriasNovaRoute: AppVistoriasNovaRoute,
  AppImoveisIndexRoute: AppImoveisIndexRoute,
  AppVistoriasIndexRoute: AppVistoriasIndexRoute,
  AppCompararABRoute: AppCompararABRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
